### ISSUE TITLE
Invite to the organization

### ISSUE THREAD

**Issue by trial1user** [PatternHouse/Join_PatternHouse#1]
hello maintainers, I have prior worked on printing patterns repository and now wish to join the organization to continue contributing pls add me as a member of patternhouse

githubID: trial1user
email: gothamherobat@gmail.com

**Comment by ChlorinePentoxide** [comment]
Hey welcome back!
Sure I will send the invite right now

**Comment by ChlorinePentoxide** [comment]
Invite sent! Please join. Make sure you check the required repos to check for available work.

**Comment by trial1user** [comment]
thanks i have joined
