### ISSUE TITLE
To join the organisation

### ISSUE THREAD

**Issue by anshyyy** [PatternHouse/Join_PatternHouse#10]
Hello there,
I would really like to join this Organization as i am new to the world of Open source , this will be my first organization to work on issues. Most importantly I will learn many things from here about contributing to open source.
Thanks,
Github email : anshuman9998@gmail.com
Github Username : https://github.com/anshyyy

**Comment by aryashah2k** [comment]
Hey there @anshyyy  , welcome to PatternHouse! I have sent the invite to join, do make your membership public so that the organization badge is visible on your profile.
