### ISSUE TITLE
Request to join the Organization

### ISSUE THREAD

**Issue by aakash232** [PatternHouse/Join_PatternHouse#11]
Hello!
I would really love to join PatternHouse.
The contributions will help me to learn and boost my knowledge. Plus it's open source hence will addOn a lot of additional social skills too. I'd love to kickstart SWoC 2.0 with this beautiful organization.
Github email : aakashtyagi232@gmail.com
Github Username : https://github.com/aakash232

Thank you

**Comment by aryashah2k** [comment]
Hey there @aakash232  , welcome to PatternHouse! I have sent the invite to join, do make your membership public so that the organization badge is visible on your profile.
