### ISSUE TITLE
Joining request

### ISSUE THREAD

**Issue by Daksh777** [PatternHouse/Join_PatternHouse#12]
Hey!
I want to join this organization to improve my logic and programming skills in Python. And since this project is open source, my contributions and knowledge will also be visible on my profile.

**Comment by aryashah2k** [comment]
Hey there @Daksh777 , welcome to PatternHouse! I have sent the invite to join, do make your membership public so that the organization badge is visible on your profile.

**Comment by Daksh777** [comment]
Thank you so much!
