### ISSUE TITLE
Join_PatternHouse

### ISSUE THREAD

**Issue by Kajal13081** [PatternHouse/Join_PatternHouse#13]
GitHub id: https://github.com/Kajal13081
GitHub username: Kajal13081
I want to join this organisation for SWOC 2.0. I would like to contribute in open source projects through this organization.

**Comment by aryashah2k** [comment]
Hey there @Kajal13081  , welcome to PatternHouse! I have sent the invite to join, do make your membership public so that the organization badge is visible on your profile.
