### ISSUE TITLE
Join_PatternHouse

### ISSUE THREAD

**Issue by HassanRahim26** [PatternHouse/Join_PatternHouse#14]
**GitHub Id:-** https://github.com/HassanRahim26
**GitHub Username:-** HassanRahim26

Hey, I'm [Hassan](https://github.com/HassanRahim26). I want to join this organisation and I'm looking forward to contribute to this organisation's amazing projects.

**Comment by aryashah2k** [comment]
Hey there @HassanRahim26  , welcome to PatternHouse! I have sent the invite to join, do make your membership public so that the organization badge is visible on your profile.
