### ISSUE TITLE
Joining Request

### ISSUE THREAD

**Issue by sohilkhanduja** [PatternHouse/Join_PatternHouse#17]
Email : khandujasohil@gmail,com
Username: sohilkhanduja
Purpose : To contribute to PatternHouse as part of SWOC 2.0.

**Comment by aryashah2k** [comment]
Hey there @sohilkhanduja  , welcome to PatternHouse! I have sent the invite to join, do make your membership public so that the organization badge is visible on your profile.

**Comment by sohilkhanduja** [comment]
Sure, thanks
