### ISSUE TITLE
Invite to join

### ISSUE THREAD

**Issue by kdgyimah** [PatternHouse/Join_PatternHouse#2]
I am a JavaScript Developer and looking forward to adding support for JavaScript as part of the mainstream languages of Pattern House
Github EmailID: kgyimah.dev@gmail.com
Github Username: kdgyimah

**Comment by aryashah2k** [comment]
Hey there buddy, an invite has been sent to your email. You can also join the organization simply by visiting the homepage of the organization on Github. Looking forward to see your contributions. You may close this issue once accepting the invite. Also dont forget to make your membership public by following instructions of the README of this repo. Good Luck!
