### ISSUE TITLE
Regarding Joining the organization

### ISSUE THREAD

**Issue by Arkaprava-Nath** [PatternHouse/Join_PatternHouse#20]
I am Arkaprava Nath
git hub email id-natharkaprava@gmail.com
git hub user name-Arkaprava Nath
It would me my pleasure to contribute to your repository.

**Comment by aryashah2k** [comment]
Hey there @Arkaprava-Nath , I have sent the invite link, do make your organization membership public so that the badge appears on your profile

**Comment by ABHIGYANSINGH77** [comment]
I'm Abhigyan Singh
git hub email- abhigyan.classroom@gmail.com
git hub user name- ABHIGYANSINGH77
Contributing to open source is always fun and a good learning experience. I will look forward to contribute to your repository.

**Comment by aryashah2k** [comment]
Hey there @ABHIGYANSINGH77 , I have sent the invite, do make your visibility to public so that the badge is displayed on your profile
