### ISSUE TITLE
joining request

### ISSUE THREAD

**Issue by VikasYadav-1** [PatternHouse/Join_PatternHouse#21]
Email : vikas_12015030@nitkkr.ac.in
Username: VikasYadav-1
 To contribute to PatternHouse as part of SWOC 2.0

**Comment by aryashah2k** [comment]
Hey there @VikasYadav-1 , welcome to PatternHouse! I have sent the invite to join, do make your membership public so that the organization badge is visible on your profile.

**Comment by VikasYadav-1** [comment]
I have joined the organization . thank you
