### ISSUE TITLE
github username: Mitz190

### ISSUE THREAD

**Issue by Mitz190** [PatternHouse/Join_PatternHouse#22]
_Hello I'm Mithali Redkar_
I would love to join the Organzition as I love open source contribution ,Open Source provides means For Learner to learn from others the beauty here is even a beginner can contribute into the projects .
I love to solve the pattern problems.
github username:Mitz190

**Comment by ChlorinePentoxide** [comment]
Thank you for checking our project. You have been invited to join the organization. :)
