### ISSUE TITLE
Issue opened to join PatternHouse

### ISSUE THREAD

**Issue by vaidehisinha1** [PatternHouse/Join_PatternHouse#26]
Hello!
My name is Vaidehi Sinha. I came across this project through the SWOC 2.0 website and would love to contribute to it, considering that its very creative and interactive. 
Github Email : 1032201688@mitwpu.edu.in
GitHub Username : vaidehisinha1
Thank you!

**Comment by aryashah2k** [comment]
Hi there, invite has been sent, do change your membership public so that badge is visible on your profile

**Comment by vaidehisinha1** [comment]
Thank you! I have accepted the invite and made my membership public.
