### ISSUE TITLE
Organization Joining Request

### ISSUE THREAD

**Issue by kashyap1905** [PatternHouse/Join_PatternHouse#28]
Hello @aryashah2k !

Name - BOBBY KUMAR
GitHub User Name - Kashyap1905
GitHub Email - kashyapashish0002@gmail.com

In the initial days of my learning, It was very difficult for me to find codes for some pattern questions. Therefore, I want to contribute to this organization so that others will not face the problems faced by me.

Also, solving pattern questions are quite interesting and it also enhances problem-solving skill.

So these are the reasons I wanted to join this organization.

**Comment by aryashah2k** [comment]
Invite sent, you can join the org and make your membership public
