### ISSUE TITLE
Organisation Joining Request

### ISSUE THREAD

**Issue by lovishprabhakar02** [PatternHouse/Join_PatternHouse#33]
Hello @aryashah2k sir!

Name -  LOVISH PRABHAKAR
GitHub User Name - lovishprabhakar02
GitHub Email - 2020010006574@gndu.ac.in

I am a new programmer so solving pattern problems is a challenge for me. Thus, I would like to contribute to the organization and simultaneously learn the skill of patterns by solving problems.

**Comment by ChlorinePentoxide** [comment]
@lovishprabhakar02 Welcome to our organization, an invite will soon be sent. Please make your membership public after joining. Thanks for checking us out.
