### ISSUE TITLE
Access to repo - SWOC mentor

### ISSUE THREAD

**Issue by kanak22** [PatternHouse/Join_PatternHouse#35]
GitHub account:- https://github.com/kanak22
GitHub Id:- kanak22

**Comment by aryashah2k** [comment]
Which repositories do you wish to have access to? Please list down the language repositories you wish to mentor and keep track of PRs and I will give maintainer access to those repos

**Comment by kanak22** [comment]
repos I want to mentor
C-PatternHouse
CPlusPlus-PatternHouse
JavaScript-PatternHouse
