### ISSUE TITLE
Request to join the Pattern House Organization

### ISSUE THREAD

**Issue by Mahak008** [PatternHouse/Join_PatternHouse#37]
Github Username : @Mahak008
I wanted to be a part of the organization in order to get knowledge about Open Source. I would like to collaborate and learn new skills and have a good experience while learning and contributing to the project. 

I wanted to mentor the **Series Pattern - Java** @aryashah2k

**Comment by aryashah2k** [comment]
Invite has been sent, Welcome to PatternHouse!
