### ISSUE TITLE
I would like to join your organization

### ISSUE THREAD

**Issue by cyberbuddy-manas** [PatternHouse/Join_PatternHouse#38]
**GitHub Username :** @cyberbuddy-manas
**Email ID :** manas@cyberbuddy.io

I want to be a part of the organization in order to get knowledge about Open Source. I would like to contribute in your organization and learn new skills and have a good experience while learning and contributing to the project. 

I can code in all the Java, JS, CPP or Python and to be unique, I can write code in **PowerShell scripts** or any scripting language @aryashah2k

**Comment by ChlorinePentoxide** [comment]
@cyberbuddy-manas Welcome, We will surely send an invite to join our organization. 

Since you mentioned PowerShell scripts I guess you can work on the Windows compatibility of our Central project (the web version of the project). Currently it is Linux-only (Makefiles), we will be happy if anyone can maintain the Windows side of things. Please let me know me if you are interested.

**Comment by aryashah2k** [comment]
Invite has been shared, welcome to PatternHouse!

**Comment by cyberbuddy-manas** [comment]
> @cyberbuddy-manas Welcome, We will surely send an invite to join our organization.
> 
> Since you mentioned PowerShell scripts I guess you can work on the Windows compatibility of our Central project (the web version of the project). Currently it is Linux-only (Makefiles), we will be happy if anyone can maintain the Windows side of things. Please let me know me if you are interested.

Definitely I'll like to work with you in the Central Project of yours if I get more details about it.

**Comment by aryashah2k** [comment]
Definitely, @ChlorinePentoxide will be able to guide you for that repo and I am also adding you to the central team so all doubts can be taken there henceforth!

**Comment by cyberbuddy-manas** [comment]
Coolx, hope for a great experience from you guys.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
