### ISSUE TITLE
I want To join This Organization

### ISSUE THREAD

**Issue by JayantGoel001** [PatternHouse/Join_PatternHouse#4]
Github Handle:- @JayantGoel001
Email:- jgoel92@gmail.com

I want to improve my skill and become a better developer.

**Comment by aryashah2k** [comment]
Welcome To PatternHouse Jayant, I have sent an invite to join this organization. You can close this issue once you accept the invite and make your membership public via settings.
Have a great day!

**Comment by JayantGoel001** [comment]
> Welcome To PatternHouse Jayant, I have sent an invite to join this organization. You can close this issue once you accept the invite and make your membership public via settings.
> Have a great day!

Yup
Thanks a lot!!🙂
