### ISSUE TITLE
Request to join Pattern House!

### ISSUE THREAD

**Issue by sanviii** [PatternHouse/Join_PatternHouse#41]
GitHub username -  sanviii

I would like to join your organization so that I can learn your way of doing stuff and start off with my open source journey!
I am good with HTML , CSS , JS , Bootstrap and Python.

**Comment by aryashah2k** [comment]
Invite has been sent! Welcome to PatternHouse

**Comment by sanviii** [comment]
@aryashah2k My invite is expired. Could you please share it again?

**Comment by aryashah2k** [comment]
sent a new one!

**Comment by sanviii** [comment]
thank you!
