### ISSUE TITLE
eshan1925 wants to join the organization.

### ISSUE THREAD

**Issue by eshan1925** [PatternHouse/Join_PatternHouse#42]
Username - @eshan1925
Email - eshan1925@gmail.com

The reason I want to join this organization is as I am a participant of SWOC and I want to contribute to the project.

**Comment by aryashah2k** [comment]
Invite has been sent. Are you a SWOC participant?

**Comment by eshan1925** [comment]
> Invite has been sent. Are you a SWOC participant?

yes

**Comment by aryashah2k** [comment]
Make sure you go through the Discord channel for PatternHouse and accustom yourself with the contribution guidelines for this project.

**Comment by eshan1925** [comment]
Sure @aryashah2k Please provide me the discord server link.

**Comment by aryashah2k** [comment]
> Sure @aryashah2k Please provide me the discord server link.

I think you might have recieved during SWOC registrations. See if this works, or else contact the authorities who sent you the SWOC email once you got accepted in the program. https://discord.com/invite/7fGa94w7Pd
