### ISSUE TITLE
Request to join pattern house.

### ISSUE THREAD

**Issue by pacific-prashant** [PatternHouse/Join_PatternHouse#43]
I want to be a part of the organization in order to get knowledge about Open Source. I would like to contribute to your organization and learn new skills and have a good experience while learning and contributing to the project. 
I'm comfortable with languages like HTML,CSS,Javascript,C++. I want to contribute in C++ / Javascript.
Looking forward to a new opportunity.

**Comment by ChlorinePentoxide** [comment]
@pacific-prashant Welcome to our organization. Will you joining the organization as part of SWoC? Regardless of this you can join our organization by the invite I will send shortly. Please do join our Discord servers (https://discord.gg/Gg8DaSQ7) and do not hesitate to say hello to the team members there.

**Comment by pacific-prashant** [comment]
yes
