### ISSUE TITLE
Reason for joining the organization 

### ISSUE THREAD

**Issue by Deepakmukka1** [PatternHouse/Join_PatternHouse#6]
Email ID : ramu92013@gmail.com
Username : Deepakmukka1
Why Do You Want To Join The Organization : I have a great interest in creating patterns , i had a personal repository of all my patterns and i found your organization with similar goals .

**Comment by aryashah2k** [comment]
Hey there, that's great to know. I have sent the invite to join, do make your membership public so that the organization badge is visible on your profile

**Comment by Deepakmukka1** [comment]
@aryashah2k Hey , i want to start contributing to cplusplus repo , are there any contributing  guidelines to be followed?
