### ISSUE TITLE
Request to join the organization

### ISSUE THREAD

**Issue by lionelsamrat10** [PatternHouse/Join_PatternHouse#8]
Github Username: lionelsamrat10
Github email id: samratmitra338@gmail.com
Purpose of joining: Want to collaborate with other fellow devs!!

**Comment by aryashah2k** [comment]
Hey there @lionelsamrat10  , welcome to PatternHouse! I have sent the invite to join, do make your membership public so that the organization badge is visible on your profile.

**Comment by lionelsamrat10** [comment]
Thanks @aryashah2k
