### ISSUE TITLE
Request to join the organization

### ISSUE THREAD

**Issue by BaseMax** [PatternHouse/Join_PatternHouse#9]
Hi Arya

**GitHub Username:**
[BaseMax](https://github.com/BaseMax/)

**GitHub Email:**
It's available on my profile page (I hate scammers)

**Purpose of joining:**
Explore something new

**Comment by aryashah2k** [comment]
Hey there @BaseMax , welcome to PatternHouse! I have sent the invite to join, do make your membership public so that the organization badge is visible on your profile.
